# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HansongTemplateProjectOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OCHamcrest'
  # Pods for HansongTemplateProjectOC

  target 'HansongTemplateProjectOCTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCHamcrest'
    pod 'Specta'
    pod 'Expecta'
    pod 'Nocilla'
    pod "Kiwi",'3.0.0'
#    pod 'CocoaHTTPServer'
    pod 'AFNetworking','4.0.1'
    pod 'MKNetworkKit','0.87'
    pod 'OHHTTPStubs'
  end

  target 'HansongTemplateProjectOCUITests' do
#    # Pods for testing
#    pod 'OCHamcrest'
#    pod 'Specta'
#    pod 'Expecta'
#    pod 'Nocilla'
#    pod "Kiwi",'3.0.0'
#    pod 'CocoaHTTPServer'
#    pod 'AFNetworking','4.0.1'
#    pod 'MKNetworkKit','0.87'
#    Installing AFNetworking (4.0.1)
#    Installing CocoaAsyncSocket (7.6.4)
#    Installing CocoaHTTPServer (2.3)
#    Installing CocoaLumberjack (3.7.0)
#    Installing MKNetworkKit (0.87)
#    Installing Reachability (3.1.1)
  end

end
